export { default } from './macro/transformer';

export type * from 'plugin/macro';
export type * from 'plugin/macro/macro';
export type * from 'lib/checks/borrow';
export type * from 'lib/checks/borrow/borrow';
export type * from 'lib/checks/borrow/$';
export type * from 'lib/checks/borrow/borrowMutable';
export type * from 'lib/checks/borrow/$$';
export type * from 'lib/checks/local';
export type * from 'lib/checks/local/local';
export type * from 'lib/checks/move';
export type * from 'lib/checks/move/move';
export type * from 'lib/checks/own';
export type * from 'lib/checks/static';
export type * from 'lib/checks/static/stack';
export type * from 'lib/core/result/index';
export type * from 'lib/core/result/ok';
export type * from 'lib/core/result/err';
export type * from 'lib/core/result/return';
export type * from 'lib/core/type';
